# Generated by Django 4.1.5 on 2023-01-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_password_id_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
