# Generated by Django 3.1.13 on 2022-12-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('approve', models.BooleanField(blank=True, default=False, help_text='FOR EMPLOYER')),
                ('accept', models.BooleanField(blank=True, default=False, help_text='FOR TASKER')),
            ],
            options={
                'db_table': 'e_bids',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='Others', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'e_categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, help_text='Write Short job tittle here', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Write Details job delivarables  here', null=True)),
                ('price', models.FloatField(blank=True, help_text='Enter amount to pay per page-KES', null=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Enter number of pages required', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Enter submission Deadline.Tip- Enter time less than the actual! ', null=True)),
                ('display', models.BooleanField(blank=True, default=False, help_text='Check this button to make your job available in the market')),
                ('state', models.BooleanField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('BK', 'booked'), ('CL', 'closed')], default='AV', max_length=100)),
            ],
            options={
                'db_table': 'e_jobs',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='pending', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'e_status',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='Others', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'e_subcategories',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='escrew', max_length=100, null=True)),
            ],
            options={
                'db_table': 'e_types',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('proof', models.TextField()),
                ('status', models.CharField(blank=True, default='pending', max_length=250, null=True)),
                ('feedback', models.CharField(choices=[('RVW', 'review'), ('RVS', 'Revise'), ('RJ', 'Rejected'), ('SC', 'Success')], default='RVW', max_length=100)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.job')),
            ],
            options={
                'db_table': 'e_submissions',
            },
        ),
    ]
