# Generated by Django 4.1.5 on 2023-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfile',
            name='title',
            field=models.CharField(blank=True, default='file', help_text='Write Short  title here', max_length=255, null=True),
        ),
    ]
