# Generated by Django 4.1.5 on 2023-01-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
