# Generated by Django 4.1.5 on 2023-01-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
