# Generated by Django 4.1.5 on 2023-01-14 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='dfile',
        ),
        migrations.AddField(
            model_name='dfile',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Upload files from your device', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.job'),
        ),
        migrations.AddField(
            model_name='dfile',
            name='title',
            field=models.CharField(blank=True, help_text='Write Short  title here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='revinfo',
            name='title',
            field=models.CharField(blank=True, help_text='Write Short title here', max_length=255, null=True),
        ),
    ]
