# Generated by Django 4.1.5 on 2023-01-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_employer_alter_job_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AlterField(
            model_name='job',
            name='dfile',
            field=models.ForeignKey(blank=True, help_text='Upload files from your device', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dfile'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
