# Generated by Django 4.1.5 on 2023-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_bid_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
