# Generated by Django 4.1.5 on 2023-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_job_dfile_dfile_job_dfile_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
