# Generated by Django 4.1.5 on 2023-01-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_job_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final',
            field=models.BooleanField(blank=True, default=False, help_text='Check for Final Submission'),
        ),
    ]
