# Generated by Django 4.1.5 on 2023-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_submission_document_alter_submission_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='revinfo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/%Y/%m/%d/'),
        ),
    ]
