# Generated by Django 4.1.5 on 2023-01-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_bid_bidder_id_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='approve',
            field=models.BooleanField(blank=True, default=False, help_text='FOR EMPLOYER', null=True),
        ),
    ]
