# Generated by Django 4.1.5 on 2023-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_bid_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='accept',
            field=models.BooleanField(blank=True, default=False, help_text='FOR TASKER', null=True),
        ),
    ]
