# Generated by Django 4.1.5 on 2023-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_bid_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('AV', 'available'), ('AV', 'in-progress'), ('AV', 'in-review'), ('AV', 'in-revision'), ('CL', 'closed')], default='AV', max_length=100),
        ),
    ]
