# Generated by Django 4.1.5 on 2023-01-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_submission_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revinfo',
            name='dfile',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='dfile',
        ),
        migrations.AddField(
            model_name='dfile',
            name='rfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.revinfo'),
        ),
        migrations.AddField(
            model_name='dfile',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.submission'),
        ),
    ]
