# Generated by Django 4.1.5 on 2023-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
