# Generated by Django 4.1.5 on 2023-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_job_accepted_job_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rejected_work_accepted',
            field=models.BooleanField(blank=True, default=False, help_text='FOR  Tasker'),
        ),
        migrations.AddField(
            model_name='job',
            name='rejection_description',
            field=models.TextField(blank=True, help_text='Write Details why you reject the work done by  tasker  here', null=True),
        ),
    ]
