# Generated by Django 4.1.5 on 2023-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_job_rejected_work_accepted_job_rejection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, help_text='FOR EMPLOYER'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rejected',
            field=models.BooleanField(blank=True, default=False, help_text='FOR EMPLOYER'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rejected_work_accepted',
            field=models.BooleanField(blank=True, default=False, help_text='FOR TASKER,SUPPORT OR ADMIN'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rejection_description',
            field=models.TextField(blank=True, help_text='FOR EMPLOYER.Write Details why you reject the work done by  tasker  here', null=True),
        ),
    ]
