# Generated by Django 4.1.5 on 2023-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_job_accepted_alter_job_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rejected_work_accepted',
            field=models.BooleanField(blank=True, default=False, help_text='FOR TASKER,SUPPORT OR ADMIN.Admin to decide if the tasker refused to ACCEPT'),
        ),
    ]
