# Generated by Django 4.1.5 on 2023-01-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_job_rejected_work_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, help_text='FOR EMPLOYER.Write Details why you reject the work done by  tasker  here', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='revise',
            field=models.BooleanField(blank=True, default=False, help_text='FOR EMPLOYER'),
        ),
        migrations.AddField(
            model_name='submission',
            name='final',
            field=models.BooleanField(blank=True, default=False, help_text='DRAFT/FINAL'),
        ),
        migrations.AddField(
            model_name='job',
            name='revise_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.revinfo'),
        ),
    ]
