# Generated by Django 4.1.5 on 2023-01-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_revinfo_remove_submission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revinfo',
            name='dfile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='revinfo',
            name='description',
            field=models.TextField(blank=True, help_text='FOR EMPLOYER.Write Details revision details  here', null=True),
        ),
    ]
