# Generated by Django 3.1.13 on 2022-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='var1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='paypill',
            field=models.IntegerField(blank=True, default=959595, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=20, null=True),
        ),
    ]
