# Generated by Django 3.1.13 on 2022-12-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.centralbank'),
        ),
    ]
