# Generated by Django 4.1.5 on 2023-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmail', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Messages',
                'db_table': 'd_contact_us',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.CharField(blank=True, default='Within deadlines', max_length=100, null=True)),
                ('m2', models.CharField(blank=True, default='At low cost', max_length=100, null=True)),
                ('m3', models.CharField(blank=True, default='At any Time', max_length=100, null=True)),
                ('m4', models.CharField(blank=True, default='With perfection', max_length=100, null=True)),
                ('m5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m6', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m7', models.CharField(blank=True, max_length=100, null=True)),
                ('message1', models.TextField(blank=True, default='We complete your tasks,from essays or eBooks to programming.', max_length=100, null=True)),
                ('message2', models.TextField(blank=True, default='With the AjiraPanel Platform, you can post any digital task ,assignement of any difficulty to be done for you.Our high profile wtitters are ready to assist you.Welcome!', max_length=300, null=True)),
                ('message3', models.TextField(blank=True, default='AjiraPanel has evolved to a platform where employers and writers co-exist. Posting orders to the public and digital payment are the trending features. It still remains to be a tool for you to manage your writers effeciently. Comes with an inbuilt plagiarism checker, ability to assign and reasign orders, track payments and balances, among other incredible features. All bundled up for you to ensure you run your operations smoothly.', max_length=300, null=True)),
                ('message4', models.TextField(blank=True, default='AjiraPanel is an Platform that sorts out your digital task management problems, by offering the ability to manage all your taskers with ease.', max_length=300, null=True)),
                ('call', models.CharField(blank=True, default='0792966490', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'EDIT HOMEPAGE',
                'db_table': 'd_index',
            },
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_hits_login', models.IntegerField(blank=True, default=0, null=True)),
                ('homepage_hits_anonymous', models.IntegerField(blank=True, default=0, null=True)),
                ('spinx_hits', models.IntegerField(blank=True, default=0, null=True)),
                ('spinx_hits_anonymous', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'd_user_stat',
                'get_latest_by': 'id',
            },
        ),
    ]
