# Generated by Django 4.1.5 on 2023-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactus_id_alter_userstat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m6', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('m7', models.CharField(blank=True, max_length=100, null=True)),
                ('message1', models.TextField(blank=True, default='We complete your tasks,from essays or eBooks to programming.', max_length=100, null=True)),
                ('message2', models.TextField(blank=True, default='With the AjiraPanel Platform, you can post any digital task ,assignement of any difficulty to be done for you.Our high profile wtitters are ready to assist you.Welcome!', max_length=100, null=True)),
                ('message3', models.TextField(blank=True, max_length=100, null=True)),
                ('message4', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'd_index',
            },
        ),
    ]
