# Generated by Django 4.1.5 on 2023-01-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='message2',
            field=models.TextField(blank=True, default='With the AjiraPanel Platform, you can post any digital task ,assignement of any difficulty to be done for you.Our high profile wtitters are ready to assist you.Welcome!', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='message3',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='message4',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
