# Generated by Django 4.1.5 on 2023-01-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_index_message2_alter_index_message3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='message3',
            field=models.TextField(blank=True, default='AjiraPanel has evolved to a platform where employers and writers co-exist. Posting orders to the public and digital payment are the trending features. It still remains to be a tool for you to manage your writers effeciently. Comes with an inbuilt plagiarism checker, ability to assign and reasign orders, track payments and balances, among other incredible features. All bundled up for you to ensure you run your operations smoothly.', max_length=300, null=True),
        ),
    ]
