# Generated by Django 4.1.5 on 2023-01-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_index_message3'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='call',
            field=models.CharField(blank=True, default='0792966490', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='message4',
            field=models.TextField(blank=True, default='AjiraPanel is an Platform that sorts out your digital task management problems, by offering the ability to manage all your taskers with ease.', max_length=300, null=True),
        ),
    ]
