# Generated by Django 4.1.5 on 2023-01-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_index_call_alter_index_message4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name_plural': 'EDIT HOMEPAGE'},
        ),
        migrations.AlterField(
            model_name='index',
            name='m1',
            field=models.CharField(blank=True, default='Within deadlines', max_length=100, null=True),
        ),
    ]
