# Generated by Django 4.1.5 on 2023-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_index_options_alter_index_m1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='m2',
            field=models.CharField(blank=True, default='At low cost', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='m3',
            field=models.CharField(blank=True, default='At any Time', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='m4',
            field=models.CharField(blank=True, default='With perfection', max_length=100, null=True),
        ),
    ]
