name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8,]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    
          
  deploy:
    runs-on: ubuntu-latest
    needs: build    
    name: deploy
    
    
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DIGITAL_OCEAN_IP }}
        username: ${{ secrets.DIGITAL_OCEAN_USER }}
        key: ${{ secrets.DIGITAL_OCEAN_KEY }}
        script: |
          mkdir -p ~/eltask
          cd ~/eltask
          source venv/bin/activate
          
          cd ~/eltask/src
            
          git pull origin master
       

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
          #create Migrations Backup Directories
                    
          mkdir -p ~/eltask/migrations/dashboard/migrations
          mkdir -p ~/eltask/migrations/users/migrations
          mkdir -p ~/eltask/migrations/home/migrations
          
          
          #RSYNC Backup Migrations To Workin Directory
          rsync -a --delete ~/eltask/migrations/dashboard/migrations ~/eltask/src/account
          rsync -a --delete ~/eltask/migrations/users/migrations ~/eltask/src/users
          rsync -a --delete ~/eltask/migrations/home/migrations ~/eltask/src/home
          
          #COLLECTSTATIC          
          cd ~/eltask/src 
          python manage.py collectstatic
          
          
          #MAKEMIGRATIONS
          cd ~/eltask/src 
          
          python manage.py makemigrations
          python manage.py makemigrations users
          python manage.py makemigrations home
          python manage.py makemigrations dashboard
          
          #_____________________________________________________________
          
          #MIGRATE-ALL
          cd ~/eltask/src  
          python manage.py migrate

          #MIGRATE-dashboard
          cd ~/eltask/src
          python manage.py migrate dashboard


          #Rsync Workin Directory to Backup Migrations-dashboard
          rsync -a --delete ~/eltask/src/dashboard/migrations ~/eltask/migrations/dashboard

          cd ~/eltask/migrations/dashboard
          tree

          #USERS
          cd ~/eltask/src
          python manage.py migrate users

         
          #Rsync Workin Directory to Backup Migrations-users Backup          
          
          rsync -a --delete ~/eltask/src/users/migrations ~/eltask/migrations/users          
          cd ~/eltask/migrations/users
          tree    


          #HOME
          cd ~/eltask/src  
          python manage.py migrate home


          # Rsync Workin Directory to Backup Migrations-home

          rsync -a --delete ~/eltask/src/home/migrations ~/eltask/migrations/home
          cd ~/eltask/migrations/home
          tree           

          #Backup Migrations_Updated

          cd ~/eltask/migrations
          ls        
          sudo shutdown -r now
        
                   
          
          
          
          
